function renew_profile = renew_profile(nt)
%RENEW_PROFILE  imports wind and PV profile data period
%   nt:     time horizon imported
%   Yaze Li, University of Arkansas

%% define constants
[GEN_BUS, PG, QG, QMAX, QMIN, VG, MBASE, GEN_STATUS, PMAX, PMIN, ...
    MU_PMAX, MU_PMIN, MU_QMAX, MU_QMIN, PC1, PC2, QC1MIN, QC1MAX, ...
    QC2MIN, QC2MAX, RAMP_AGC, RAMP_10, RAMP_30, RAMP_Q, APF] = idx_gen;
[CT_LABEL, CT_PROB, CT_TABLE, CT_TBUS, CT_TGEN, CT_TBRCH, CT_TAREABUS, ...
    CT_TAREAGEN, CT_TAREABRCH, CT_ROW, CT_COL, CT_CHGTYPE, CT_REP, ...
    CT_REL, CT_ADD, CT_NEWVAL, CT_TLOAD, CT_TAREALOAD, CT_LOAD_ALL_PQ, ...
    CT_LOAD_FIX_PQ, CT_LOAD_DIS_PQ, CT_LOAD_ALL_P, CT_LOAD_FIX_P, ...
    CT_LOAD_DIS_P, CT_TGENCOST, CT_TAREAGENCOST, CT_MODCOST_F, ...
    CT_MODCOST_X] = idx_ct;
%% import wind profile from t to t+nt-1
% Note that testing set is used for ACOPF
base = 100;
profile = load('profile.mat');
renew_no = [1,2,3,4];

% MOST scale the wind by base power
Renew = repmat((profile.wind+profile.pv),4,1)'/base;
% Construct wind profile structure
renew_profile = struct( ...
    'type', 'mpcData', ...
    'table', CT_TGEN, ...
    'rows', renew_no, ...
    'col', PMAX, ...
    'chgtype', CT_REL, ...
    'values', [] );
renew_profile.values(:, 1, :) = Renew; 
