function renew = renew(bus_no)
%RENEW models renewable source as a generator at given bus for case14mdf
%   bus_no: bus number where the renewable energy is connected
%   Yaze Li, University of Arkansas

%% generator data
%	bus	Pg	Qg	Qmax	Qmin	Vg	mBase	status	Pmax	Pmin	Pc1	Pc2	Qc1min	Qc1max	Qc2min	Qc2max	ramp_agc	ramp_10	ramp_30	ramp_q	apf
renew.gen = [
	bus_no	0	0	50	-50	1	100	1	100	0	0	0	0	0	0	0	0	200	200	0	0;
];
%% xGenData
renew.xgd_table.colnames = {
	'CommitKey', ...
		'CommitSched', ...
			'InitialPg', ...
				'RampWearCostCoeff', ...
					'PositiveActiveReservePrice', ...
						'PositiveActiveReserveQuantity', ...
							'NegativeActiveReservePrice', ...
								'NegativeActiveReserveQuantity', ...
									'PositiveActiveDeltaPrice', ...
										'NegativeActiveDeltaPrice', ...
											'PositiveLoadFollowReservePrice', ...
												'PositiveLoadFollowReserveQuantity', ...
													'NegativeLoadFollowReservePrice', ...
														'NegativeLoadFollowReserveQuantity', ...
};

renew.xgd_table.data = [
	2	1	0	0	1e-8	200	2e-8	200	1e-9	1e-9	1e-6	200	1e-6	200;
];
